apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: alert-consumer
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-source
    properties:
      brokers: "messaging-kafka-broker-kafka-bootstrap.messaging-kafka-broker:9092"
      topic: "smart-nano.alerts"
  sink:
    uri: "log:info"